# config.yaml
# 
# paths are relative to the working directory of the script
model_path: "./pan_cancer/best_model.pt"
vocab_json: "./pan_cancer/vocab.json"
args_json: "./pan_cancer/args.json"
adata_path: "./data/c_data.h5ad"
adata_filtered_path: "./data/filtered_ms_adata.h5ad"
output_dir: "./save/scgpt_run/"
wandb_api_key: ""      # wandb api key, optional if already configured, otherwise set it here
wandb_project: "scGPT" # optional, the name of the wandb project

