# config_general.yml
# Generalization of scGPT finetune cell annotation

# --- paths ---
model_path: "../pan_cancer/best_model.pt"
vocab_json: "../pan_cancer/vocab.json"
args_json: "../pan_cancer/args.json"

# --- datasets ---
adata_path: "../data/c_data.h5ad"                   # jeu d’entraînement
adata_filtered_path: "../data/filtered_ms_adata.h5ad"  # jeu de test
output_dir: "./save/scgpt_run_general/"

# --- specific keys in AnnData ---
celltype_key: "Factor Value[inferred cell type - authors labels]"
batch_key: "str_batch"
gene_name_key: "gene_name"
pred_key: "predictions"
label_id_key: "celltype_id"

# --- wandb ---
wandb_api_key: ""
wandb_project: "scGPT"

# --- hyperparameters ---
seed: 0
dataset_name: "ms"
do_train: true
mask_ratio: 0.0
epochs: 10
n_bins: 51
MVC: false
ecs_thres: 0.0
dab_weight: 0.0
lr: 1e-4
batch_size: 32
layer_size: 128
nlayers: 4
nhead: 4
dropout: 0.2
schedule_ratio: 0.9
save_eval_interval: 5
fast_transformer: true
pre_norm: false
amp: true
include_zero_gene: false
freeze: false
DSBN: false
